### ISSUE TITLE
Non-UTF8 string interop

### ISSUE THREAD

**Issue by fmckeogh** [zshipko/ocaml-rs#104]
`FromValue` is implementing for `std::string::String`, however while OCaml strings may contain arbitrary bytes Rust upholds several invariants on `String`, namely being valid UTF-8. For this reason I think `FromValue` should instead be implemented for `std::ffi::OsString` and the `String` implementations deprecated or comments adjusted to include a warning that panics can occur if the OCaml string passed is not UTF-8.

**Comment by fmckeogh** [comment]
Actually never mind, `OsString` would break platform independence.

**Comment by zshipko** [comment]
Another approach could be to implement `FromValue` for `Result<String, std::string::Utf8Error>` instead of `String`. I will give this some thought for the 1.0.0 release.

**Comment by fmckeogh** [comment]
@zshipko  Thanks! I just had some panics on `Utf8Error` that I couldn't do anything about other than take a `Vec<u8>` instead, but after thinking about it the current implementation is fine: if you care about being absolutely correct then `Vec<u8>` *is* the most accurate type to model OCaml strings; they can contain any byte sequence and aren't null terminated. If you know you're dealing with UTF-8 data on both sides then you can just use `String`.
