### ISSUE TITLE
Please add more examples to the `rust-ocaml-starter` project

### ISSUE THREAD

**Issue by emchristiansen** [zshipko/ocaml-rs#108]
The `rust-ocaml-starter` project demonstrates how to wrap a simple "Hello World" function to make it callable in Rust.
Here are the contents of [`rust_ocaml_starter.ml`](https://github.com/zshipko/rust-ocaml-starter/blob/main/lib/rust_ocaml_starter.ml):

```ocaml
let hello_world () = "Hello, world!"

let () = Callback.register "hello_world" hello_world
```

However, it doesn't specify (nor can I find in the documentation) how to wrap an example like this:

```ocaml
type t = A | B of int

let maybe_inc (t : t): t =
  match t with
    | A -> A
    | B x -> B (x + 1)
```

Could you explain how this could be done, and ideally update `rust-ocaml-starter`?
Or if you could just give me an idea of what to do I could send a pull request to `rust-ocaml-starter`.

Also, is it possible to wrap "opaque" OCaml types in Rust, e.g. network connections?
E.g. can I wrap code like this?

```ocaml
(* NetworkConnection.t is a complicated type that I don't want to fully wrap.
   But, I do want to construct it in OCaml and pass a reference to it back to Rust. *)
let make_network_connection (): NetworkConnection.t = ...

(* Later I'll invoke this function from Rust. *)
let use_network_connection (conn: NetworkConnection.t): unit = ...
```

Thanks!

**Comment by zshipko** [comment]
Thanks for pointing that out - a better example would probably be helpful!

For your code I think it would look something like this:

src/main.rs:
```rust
#[derive(ocaml::ToValue, ocaml::FromValue, Debug)]
pub enum T {
    A,
    B(ocaml::Int),
}

ocaml::import! {
    fn maybe_inc(t: T) -> T;
}

fn main() {
    let gc = ocaml::runtime::init();

    unsafe {
        println!("{:?}", maybe_inc(&gc, T::B(1)).unwrap());
    }
}
```

lib/rust_ocaml_starter.ml:
```ocaml
type t = A | B of int

let maybe_inc (t : t): t =
  match t with
    | A -> A
    | B x -> B (x + 1)

let () = Callback.register "maybe_inc" maybe_inc
```

If you wanted to add something like this to the `rust-ocaml-starter` repo that would be great! 

And opaque values can be passed using `ocaml::Value` which doesn't perform any kind of conversion when passing the OCaml value between OCaml and Rust.

**Comment by emchristiansen** [comment]
Sent a pull request here:
https://github.com/zshipko/rust-ocaml-starter/pull/1
