### ISSUE TITLE
OCaml callbacks as arguments

### ISSUE THREAD

**Issue by mimoo** [zshipko/ocaml-rs#113]
Hello,

I'd like to write a Rust functions that can take OCaml functions/callbacks as arguments. It looks like it is not possible with ocaml-rs (although I might be missing something). Any idea how I could achieve that :D?

**Comment by zshipko** [comment]
There's no way to accept a typed function as an argument, but you can use a `Value` argument for any OCaml type.

On the 1.0.0-beta versions you can use the `function!` macro to call it, or in previous versions you can use the `Value::call` functions: https://docs.rs/ocaml/0.22.4/ocaml/enum.Value.html#method.call

**Comment by mimoo** [comment]
interesting :D thanks!
