### ISSUE TITLE
v1.0.0 release?

### ISSUE THREAD

**Issue by Lupus** [zshipko/ocaml-rs#127]
It seems that the book already includes examples using features from beta 1.0.0 release, while cargo installs 0.22.4 and the examples do not work. Do you have any tentative timelines for releasing it out of beta? Is it safe to be used in current beta state?

**Comment by zshipko** [comment]
Yes, the current 1.0.0 beta should be safe to use and is more-or-less ready to be released.

There are still a few more upstream changes to support OCaml 5 I was hoping to get in before releasing 1.0, but it might make sense to just publish what I have now and make a new release once that all comes together.

**Comment by Lupus** [comment]
You could always start a new beta release branch for OCaml 5 support. As a user I would vote for a release of all those goodness that I found in the changelog for 1.0.0 beta! 😊

**Comment by dannywillems** [comment]
Hey. Is there any update on OCaml 5 support?

**Comment by zshipko** [comment]
Hey @dannywillems - I recently made the 1.0 release with OCaml 5 support, all the tests are passing using 5.1 and 5.2 but there isn't any additonal support for working with domains or anything like that.
