### ISSUE TITLE
compact.h removed from OCaml

### ISSUE THREAD

**Issue by patrick-nicodemus** [zshipko/ocaml-rs#153]
As part of the following commit:

https://github.com/ocaml/ocaml/commit/bdd8d960345a293f6643f279ab535b5637b4a34e#diff-9440250fac495dfa460155da502b2d7c7732b2bf6b852ef68de0a81d4c122905

the header file `caml/compact.h` was removed.
The vendored C code for boxroot expects this header file.
```
cargo:warning=vendor/boxroot/boxroot.c:23:10: fatal error: caml/compact.h: No such file or directory
  cargo:warning=   23 | #include <caml/compact.h>
  cargo:warning=      |          ^~~~~~~~~~~~~~~~
  cargo:warning=compilation terminated.
```

**Comment by zshipko** [comment]
Thanks, this seems like it should be reported to the ocaml-boxroot project instead: https://gitlab.com/ocaml-rust/ocaml-boxroot

**Comment by tizoc** [comment]
That is probably an old version of boxroot, I don't think the current one needs `caml/compact.h`. What were you trying to build when you got that error @patrick-nicodemus ?

**Comment by zshipko** [comment]
Ah yeah, thanks for pointing that out - it does seem that `caml/compact.h` is no longer used in `boxroot.c`

**Comment by patrick-nicodemus** [comment]
@tizoc Ah, okay, I see. Yes, `caml/compact.h` is used in version 0.2.0 of the `ocaml-boxroot-sys` crate, but not in later versions. And I see that the current master branch of this github requires version 0.2.0. However, the `ocaml` crate on crates.io specifies version 0.2.0 of `ocaml-boxroot-sys`, so the issue affects users who try to use the most recent version of the `ocaml` crate.

Additionally, the master branch of `ocaml-interop` still requires version 0.2.0, although this is a matter for an issue on a different repository.

**Comment by zshipko** [comment]
The beta release on crates.io should be using the latest `ocaml-boxroot-sys`, but that isn't shown by default - I am planning on making a 1.0 release in the next couple of weeks, so I will leave this open until then in case anyone else runs into this issue.
