### ISSUE TITLE
Misleading documentation of nativeint_val

### ISSUE THREAD

**Issue by Enkelmann** [zshipko/ocaml-rs#16]
The two functions `Value::isize_val` and `Value::nativeint_val` have exactly the same documentation, while being fundamentally different: The former converts from an Ocaml integer, the latter unwraps a native integer wrapped in a custom value.

This difference can lead to segfaults if one confuses them (as I did). Could you clarify the documentation so that others don't have to make the same mistake?

**Comment by zshipko** [comment]
Thanks for pointing this out! I am working on an update right now and will publish it in the next hour or so.

**Comment by zshipko** [comment]
Here it is: https://docs.rs/ocaml/0.9.2/ocaml/ and https://docs.rs/ocaml/0.9.2/ocaml/value/struct.Value.html#method.nativeint_val

Thanks again!
