### ISSUE TITLE
value conversion 

### ISSUE THREAD

**Issue by progman1** [zshipko/ocaml-rs#30]
with the auto conversion for a slice:
```
unsafe fn as_slice<'a>(value: Value) -> &'a [Value] {
    ::core::slice::from_raw_parts(
        (value.0 as *const Value).offset(-1),
        crate::sys::wosize_val(value.0) + 1,
    )
}
```
what's the idea behind the offset and increasing the count?

**Comment by zshipko** [comment]
I'm not 100% sure about the implementation, but it was added here: https://github.com/zshipko/ocaml-rs/pull/3/files#diff-5f9774c7d39ddf05e96907903e65733fR122 to support the deep clone functionality. 

In the general case (for arrays) it does seem to be incorrect... I've added some tests and fixed up this `as_slice` function. The original implementation is still used by the deep clone functions.

**Comment by zshipko** [comment]
Just made a new release with these changes too

**Comment by progman1** [comment]
thanks again!

**Comment by progman1** [comment]
ah, cloning - to include the header.
don't forget the poor mut version of as_slice!

**Comment by zshipko** [comment]
Thanks - I missed that one, should be updated now!
