### ISSUE TITLE
custom-ops  .identifier not set?

### ISSUE THREAD

**Issue by progman1** [zshipko/ocaml-rs#32]
in using the custom! macro I noticed the ops.identifier field was not being set as per the distro source.
replacing with a pre-expanded version showed a test .name was not copied across and .identifier was null on inspection.
can you reproduce?

**Comment by zshipko** [comment]
If `name` is non-null then the `identifier` field should be set once `Custom::ops` is called: https://github.com/zshipko/ocaml-rs/blob/master/src/custom.rs#L89

This should be called anytime you use `Value::alloc_custom` or `Pointer::alloc_custom` - are you allocating a custom type another way?

**Comment by progman1** [comment]
I over-rode ops() and
```
        Self::TYPE.ops.identifier = Self::TYPE.name.as_ptr() as *const ocaml::sys::Char;
 ```
is NOT sticking!
a print on the very next line show them as still different....

**Comment by zshipko** [comment]
Can you show me the new `ops` implementation and the code where you set the identifier field?

**Comment by progman1** [comment]
```
    fn ops() -> &'static ocaml::custom::CustomOps {
        Self::TYPE.ops.identifier = Self::TYPE.name.as_ptr() as *const ocaml::sys::Char;
        if let Some(x) = Self::TYPE.fixed_length {
            Self::TYPE.ops.fixed_length = &x;
        }

        Self::TYPE.ops.identifier = Self::TYPE.name.as_ptr() as *const ocaml::sys::Char;
let cstr = unsafe{ CStr::from_ptr( unsafe{ Self::TYPE.ops.identifier }) };
println!("haha!!!!!!!!!!!!!! {:?}", Self::TYPE.name);
println!("haha!!!!!!!!!!!!!! {:?}", CStr::to_str(cstr));
        &Self::TYPE.ops
    }
```
....excuse the coding 'style'!

**Comment by progman1** [comment]
only overriding to find the bug

**Comment by zshipko** [comment]
Hm, I'm guessing this is because `TYPE` is `const`, I will see if there's a better way to handle this

**Comment by zshipko** [comment]
@progman1 I've pushed some changes to fix this: https://github.com/zshipko/ocaml-rs/commit/9850cdb7339b26d4b649cc7ae53dcfc55e79d450. Nothing should change if you're using the `custom!` macro, otherwise a few things have been shifted around in the `Custom` internals.

**Comment by progman1** [comment]
great, thanks.
incidentally, in copying your macro I came across an oddity that scanning the docs hasn't demystified:
where the macro uses $ as below, when I replaced with 'ocaml' the compiler complained.
removing the $ sorted it but why did it work in your context and not mine?
```
const OPS: $crate::custom::CustomOps

==> const OPS: ocaml::custom::CustomOps
```

**Comment by zshipko** [comment]
https://doc.rust-lang.org/1.7.0/book/macros.html#the-variable-crate
