### ISSUE TITLE
Example of calling OCaml functions using `Value::named`

### ISSUE THREAD

**Issue by tizoc** [zshipko/ocaml-rs#35]
I'm trying to call an OCaml function from a Rust program. It is failing to obtain the registered function when using `Value::named`. I'm very new to Rust so I may be missing something, but I checked and the binary I produced contains the symbols from the object file generated by OCaml (it is being linked statically). Is there any initialization required that I am missing?

Rust code:
```rust
use ocaml::Value;
use ocaml::{ToValue, FromValue};

fn ocaml_twice(n: i32) -> i32 {
    let twice: Value = Value::named("twice").expect("Missing 'twice' function");
    let result = twice.call(n.to_value()).unwrap();
    return i32::from_value(result);
}

fn main() {
    ocaml::runtime::init();
    let result = ocaml_twice(10);
    println!("Result: {}", result);
    ocaml::runtime::shutdown();
}
```

OCaml code:
```ocaml
let twice x = 2 * x

let () = Callback.register "twice" twice
```

Dune file:
```
(executables
 (names callable)
 (modes object))
```

The cargo file contains:
```
[dependencies.ocaml]
version = "0.14.2"
features = ["link"]
```

`build.rs`:

```rust
use std::env;
use std::process::Command;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dune_dir = "../_build/default/ocaml-code";
    Command::new("dune")
        .args(&["build", "../ocaml-code/callable.exe.o"])
        .status()
        .expect("Dune failed");
    Command::new("cp")
        .args(&[
            //&format!("{}/.callable.eobjs/native/dune__exe__Callable.o", dune_dir),
            &format!("{}/callable.exe.o", dune_dir),
            &format!("{}/libcallable.o", out_dir),
        ])
        .status()
        .expect("File copy failed.");
    Command::new("rm")
        .args(&["-f", &format!("{}/libcallable.a", out_dir)])
        .status()
        .expect("rm failed");
    Command::new("ar")
        .args(&[
            "qs",
            &format!("{}/libcallable.a", out_dir),
            &format!("{}/libcallable.o", out_dir),
        ])
        .status()
        .expect("ar failed");

    println!("cargo:rustc-link-search={}", out_dir);
    println!("cargo:rustc-link-lib=static=callable");
}
```

**Comment by zshipko** [comment]
I was able to get this to build/run correctly by switching the types in  your `ocaml_twice` function:

```
fn ocaml_twice(n: ocaml::Int) -> ocaml::Int {
    let twice: Value = Value::named("twice").expect("Missing 'twice' function");
    let result = twice.call(n.to_value()).unwrap();
    return ocaml::Int::from_value(result);
}
```

This is because `i32` maps to OCaml's `Int32` type.

**Comment by tizoc** [comment]
Thank you. How are you linking it? What is failing for me is the call to `Value::named("twice")` (I'm testing this on OSX btw).

It is like the initialization part of the OCaml module I defined is never executed, so "twice" never gets registered.

**Comment by zshipko** [comment]
Here's my example code: [example.zip](https://github.com/zshipko/ocaml-rs/files/4885306/example.zip) - I am on linux, so it could be that this is an issue on macOS...

The layout is a bit different (had to change some stuff in build.rs) but the idea should be the same.

**Comment by tizoc** [comment]
Ok, just tried you version, and it fails in the same way as mine, it seems to be an OSX-specific issue.

**Comment by tizoc** [comment]
Btw, the implementation from this article works fine: https://blog.s-m.ac/ocaml-rust-ffi/

Unless I'm misunderstanding, In that case the OCaml runtime comes from the object file produced by dune, I'm going to try a variation without using `ocaml::runtime::init` and without the `link` feature.

**Comment by zshipko** [comment]
Alright, I will have to test it out on a different computer later. Thanks for reporting, I'm not often on macOS.

**Comment by zshipko** [comment]
I also added a CI test for named values: https://github.com/zshipko/ocaml-rs/commit/52ce682a7b72db32ebcffe66ec8d12da06f56a3c

That runs on macOS, so should help figure out if it's an issue when using `link` or something more general

**Comment by tizoc** [comment]
@zshipko I recompiled without the link flag and added my own runtime initialization function (which is just a copy of `ocaml::runtime::init`, and now the code runs fine.

**Comment by tizoc** [comment]
Should the "link" feature be a requirement for the `init` function?

I think what is going on is that rust is linking everything in when producing the binary, but in my case the runtime that has been linked into ocaml-rs wins over the runtime in the object files produced by dune.

The OCaml runtime that is bundled with `ocaml-rs` doesn't know anything about the data and code segments that come from the OCaml object files, so [this initialization](https://github.com/ocaml/ocaml/blob/trunk/runtime/startup_nat.c#L57-L89) never happens for the new code (by inspecting the binary I see that those segments are indeed in there).

**Comment by zshipko** [comment]
Interesting, I have no problem enabling `init` without the link feature - just pushed a commit to allow that.

I still would like to see if I can get the original example to work, since it does work on Linux. I'll keep you updated on that!

**Comment by zshipko** [comment]
Actually, thinking about it - this use case is much more common than the need to link the OCaml libraries from the Rust side. 

I will need to see if I can figure out how to clean up this process a bit - definitely open to any ideas if you have any.

**Comment by tizoc** [comment]
Here are the symbols in my ocaml code object file (`symbols libcallable.o | grep caml_globals`):

```
0x0000000000019ff9 (    0x17) caml_globalsym [FUNC, EXT, NameNList, MangledNameNList, NList] 
0x000000000002d168 (    0x60) caml_globals [EXT, NameNList, MangledNameNList, NList] 
0x000000000002d1c8 (   0x618) caml_globals_map [EXT, NameNList, MangledNameNList, NList] 
0x0000000000034bc8 (     0x8) caml_globals_inited [EXT, NameNList, MangledNameNList, NList] 
0x00000000000351a0 (     0x8) caml_globals_scanned [NameNList, MangledNameNList, NList] 
```

Executable without "link" feature (`symbols program | grep caml_globals`):

```
0x0000000100022b39 (    0x17) caml_globalsym [FUNC, EXT, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
0x0000000100061088 (    0x60) caml_globals [EXT, NameNList, MangledNameNList, NList] 
0x00000001000610e8 (   0x618) caml_globals_map [EXT, NameNList, MangledNameNList, NList] 
0x00000001000683f8 (     0x8) caml_globals_inited [EXT, NameNList, MangledNameNList, NList] 
0x0000000100069410 (     0x8) caml_globals_scanned [NameNList, MangledNameNList, NList] 
```

Executable with "link" feature enabled:

```
0x000000010002c8f1 (    0x17) caml_globalsym [FUNC, EXT, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
0x000000010006c598 (    0x18) caml_globals [EXT, NameNList, MangledNameNList, NList] 
0x000000010006c5b0 (    0x98) caml_globals_map [EXT, NameNList, MangledNameNList, NList] 
0x000000010006cdd0 (     0x8) caml_globals_scanned [NameNList, MangledNameNList, NList] 
0x000000010009d820 (     0x8) caml_globals_scanned [NameNList, MangledNameNList, NList] 
0x00000001000ce3e8 (     0x8) caml_globals_inited [EXT, NameNList, MangledNameNList, NList] 
```

So in my case the Rust compiler is indeed choosing the previously linked runtime over whats in the OCaml produced object files.

Being unfamiliar with Rust and the build process, at first I thought the "link" feature had to do about having cargo/rustc link the ocaml runtime into the final lib/executable. I was surprised because I would have expected for the linker to fail (or at least warn me) about duplicated symbols.

I'm not sure what should be done yet. 

The use case for "link" would be to be able to dynamically load ocaml code, right? (like with [Dynlink](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Dynlink.html) I suppose). So maybe it is not such an uncommon use case.

So it seems to only cause problems when the OCaml code is being statically linked, so two possible changes are:

- Don't make "link" a requirement for `ocaml::runtime::init`.
- Document that it should not be used when linking OCaml code statically because of possible conflicts.

Maybe it is possible to statically link the OCaml object files without including the runtime, but in that case the code and data blocks should be made visible to the OCaml runtime linked into ocaml-rs so that they are initialized, but I'm not sure if it is possible.

**Comment by zshipko** [comment]
I've just put out a new release where `link` isn't required to access `ocaml::runtime::init` and I've added a note about the static linking issue to the README.

**Comment by tizoc** [comment]
Thank you!
