### ISSUE TITLE
`CamlRootsBlock` uses `usize` for `ntables` and `nitems` fields, but in OCaml `intnat` (`isize`) is used instead.

### ISSUE THREAD

**Issue by tizoc** [zshipko/ocaml-rs#42]
Hi @zshipko! I'm looking into using `ocaml-sys` as a dependency to [ocaml-interop](https://github.com/simplestaking/ocaml-interop).

So far it is going well, but I noticed that in `ocaml-sys` the `ntables` and `nitems` fields [are defined as usize](https://github.com/zshipko/ocaml-rs/blob/cf19a87c8e348e7705a82d9538ced77709e854d3/sys/src/memory.rs#L47-L48), but [in OCaml those are defined as `intnat`](https://github.com/ocaml/ocaml/blob/6dc2457036d81145a61e26fec8570484dfd334b3/runtime/caml/memory.h#L271-L272), which is just an [int/long](https://github.com/ocaml/ocaml/blob/06162616426d8689f868ec9b150c6b6a9ba7fdb9/runtime/caml/config.h#L128-L145).

If done on purpose, why the difference?

NOTE: not a blocker for ocaml-interop because I'm using a different `CamlRootsBlock` representation (single local_roots pointer instead of an array of 5 pointers), so I still have to cast the pointers, just something I noticed.

**Comment by zshipko** [comment]
Hey, thanks for pointing that out. I don't think those should be `usize` - I will make that update when I get a chance!

**Comment by tizoc** [comment]
Ok, great!

**Comment by zshipko** [comment]
I've just pushed a fix here: https://github.com/zshipko/ocaml-rs/commit/b6e3da7521e6d40002690deca3794ab2208af1d8 and have released a new version to crates.io

**Comment by tizoc** [comment]
You beat me to it, was about to make a PR including this plus a few other small changes. Will rebase against master and send soon.

**Comment by zshipko** [comment]
Oops, sorry about that. I will watch out for your PR!
