### ISSUE TITLE
doc link is broken

### ISSUE THREAD

**Issue by c-cube** [zshipko/ocaml-rs#5]
documentation url https://docs.rs/ocaml/0.4.3/ocaml/ doesn't lead anywhere

**Comment by jorisgio** [comment]
the link is correct, this is actually a consequence of issue #4 
https://docs.rs/crate/ocaml/0.4.3/builds/113491
docs.rs is currently trying to build with some dev version of rust 1.28 which does not support stable repr(transparent) yet so doc build fails.

**Comment by c-cube** [comment]
Oh, makes sense. Thank you.
