### ISSUE TITLE
Possibility for invalid memory address when allocating tuples

### ISSUE THREAD

**Issue by tizoc** [zshipko/ocaml-rs#52]
Just had this bug in ocaml-interop while writing some macros to get rid of the code duplication on my tuple conversions code, and decided to check `ocaml-rs` because it was a possible issue here too, and indeed there it was.

This code here: https://github.com/zshipko/ocaml-rs/blob/dc1de3c250b48428a820c362504acc518806cf6f/src/value.rs#L318

Which is called from the tuple macros: https://github.com/zshipko/ocaml-rs/blob/dc1de3c250b48428a820c362504acc518806cf6f/src/conv.rs#L121

Reads `self.0` before converting the value that is going to be stored in the field.

This is what I am doing on my macro to avoid the issue:

```rust
macro_rules! tuple_to_ocaml {
    ($($n:tt: $t:ident => $ot:ident),+) => {
        unsafe impl<$($t),+, $($ot: 'static),+> ToOCaml<($($ot),+)> for ($($t),+)
        where
            $($t: ToOCaml<$ot>),+
        {
            fn to_ocaml<'a>(&self, cr: &'a mut OCamlRuntime) -> OCaml<'a, ($($ot),+)> {
                let len = $crate::count_fields!($($t)*);

                unsafe {
                     // 1) root the tuple value
                    let ocaml_tuple: BoxRoot<($($ot),+)> = BoxRoot::new(alloc_tuple(cr, len));
                    $(
                        // Perform the field value conversion first (GC may run here)
                        let field_val = self.$n.to_ocaml(cr);
                        // Deref the tuple value here in case it moved
                        store_field(ocaml_tuple.get_raw(), $n, field_val.get_raw());
                    )+

                    cr.get(&ocaml_tuple)
                }
            }
        }
    };
}
```

An alternative (which is what my original written-by-hand code did) is to perform all the conversions before allocating the tuple block, and then perform the assignments. But this requires that you root all the values too, because they may move before you assign the tuple fields.

**Comment by tizoc** [comment]
Oh, and in case you find it useful, I published the `ocaml-boxroot-sys` crate here: https://crates.io/crates/ocaml-boxroot-sys

The ocaml-interop code that wraps it is here: https://github.com/simplestaking/ocaml-interop/pull/27/files#diff-1f5375281f8413d0ae5b30e5b694ce3aa81e4279476d802aeb1e7ab9e67f027c

**Comment by zshipko** [comment]
Thanks for reporting! I will look into fixing this when I get a moment

**Comment by zshipko** [comment]
Hm, it looks like this also affects arrays, at least, but probably other types as well. I will look into converting this crate to use boxroots since that seems like the safest option. But, since boxroots seem close to complete, it might also be a good time to start looking at porting `ocaml-derive` over.

**Comment by tizoc** [comment]
Yes, you will find this pattern on any place where you allocate an OCaml block and then fill it with data. Boxroots is one option, because IMO they made almost everything simpler (the part that gets more complicated is that they require extra initialization at startup + teardown when the program ends). But if you don't want to do that yet, all you need is to allocate a local root to be able to re-reference the block pointer in case it moves.
