### ISSUE TITLE
Call overhead

### ISSUE THREAD

**Issue by crackcomm** [zshipko/ocaml-rs#57]
Hey, I had my code locked to revision [8bfcd27](https://github.com/zshipko/ocaml-rs/commit/8bfcd27b0abce77a8612fc77f4f30526bb1c8970) and since I updated the overhead of a call went from `11ns` up to `196ns`. I guess some of the speed was sacrificed for security but this seems huge, is there anything I can do about it? I want to find the reason and fix it if possible but a lot of changes were made so you might be able to guide me where to look for the cause.

**Comment by tizoc** [comment]
@crackcomm hello, some questions:

- how are you declaring the OCaml functions?
- to what version did you update to? 20.0? 
- can you compare speed with 19.1 and 20.0?

**Comment by zshipko** [comment]
If I had to guess without any further information, I suspect the frame macro: https://github.com/zshipko/ocaml-rs/blob/e3ed57c3f86ec85d5c02ae96af479f49b599581d/src/macros.rs#L9

Before 0.19 this implementation was much simpler with no private struct.

Once I get some time to update to the latest ocaml-interop this issue could go away since that macro will probably be removed. It’s definitely still worth trying to figure out what the cause of the slowdown is in the case that’s not the issue.

**Comment by tizoc** [comment]
Oh, so what would be useful is to see the difference between 18.x and 19.x then, not 19.x and 20.x as I asked, right?

Btw in ocaml-interop local frames are not used anymore, I use BoxRoots for everything which simplified things quite a bit.

**Comment by zshipko** [comment]
Sorry, you’re right `0.19` had the simpler frame implementation as well.

My goal is to switch over to BoxRoots in ocaml-rs as well, I just need a good chunk of time to sit down and convert everything.

**Comment by crackcomm** [comment]
> * how are you declaring the OCaml functions?

Performance of both `ocaml::func` and `ocaml::native_func` is affected.

> * to what version did you update to? 20.0?

20.0 and git master

**Comment by zshipko** [comment]
Thanks! Since things are kind of in flux right now, it might make sense to hold off on updating until the next version comes out. I am hoping to have better integration with ocaml-interop and the struct I mentioned above will be removed. 

Is your test code available somewhere?

**Comment by crackcomm** [comment]
I tried to regress and so far I found it's most likely in these [commits](https://github.com/zshipko/ocaml-rs/compare/9bb7e17e97f66034e8c5a4cee08a053672bd4e8d...bc6917804866126fdf7deb4cb08f808da36a9e55). 

I [uploaded](https://github.com/crackcomm/ocaml-rs-bench) relevant benchmark.

**Comment by tizoc** [comment]
Ok, that `__Values` thing you linked @zshipko looks suspect. But it is not entirely clear to me what is going on there. Why is that required? because of variable name shadowing?

**Comment by tizoc** [comment]
Ok, I also see from your benchmark that the overhead is there even when there are no parameters involved, so it is not necessarily about that.

**Comment by crackcomm** [comment]
This is how expanded `native_func` looks like:

```Rust
#[no_mangle]
pub unsafe extern "C" fn native_func() -> ocaml::Value {
    {
        #[allow(unused_variables)]
        let mut gc = ::ocaml::Runtime::init();
        #[cfg(not(feature = "no-std"))]
        ::ocaml::init_panic_handler();
        #[allow(unused_mut)]
        let mut r = |gc: &mut ::ocaml::Runtime| ocaml::Value::none();
        r(&mut gc)
    }
}
```

The call overhead without `ocaml::Runtime::init()` is `3.88ns`.

**Comment by tizoc** [comment]
@crackcomm I was looking exactly at that right now, and it doesn't look entirely right.

@zshipko this line:

```rust
let mut gc = ::ocaml::Runtime::init();
```

should instead be something like:

```rust
let mut gc = unsafe { ::ocaml::Runtime::::recover_handle() };
```

right?

And that is what you then pass to `ocaml::interop::interop::ocaml_frame!`

@crackcomm can you try changing that in your local version and see if that fixes the issue?

**Comment by crackcomm** [comment]
@tizoc changing it to `recover_handle` makes it `9.25ns` which is about where it was previously.

**Comment by tizoc** [comment]
@crackcomm perfect, that was it. The problem is that the current call performs the initialization every time, thats from where the overhead comes from. `recover_handle()` just gives you what you need without having to go through any initialization.

**Comment by crackcomm** [comment]
Cool, it would be good idea to integrate the benchmark as simple as it is to CI.

**Comment by tizoc** [comment]
I sill submit a PR with the fix in a bit. My bad, I should have caught this when reviewing the ocaml-interop related changes.

**Comment by crackcomm** [comment]
If it's faster I'm happy anyway, if it's not no biggie :)

**Comment by crackcomm** [comment]
I will submit a PR with benchmarks so at least it can be tracked.

**Comment by tizoc** [comment]
Fix here https://github.com/zshipko/ocaml-rs/pull/59

**Comment by tizoc** [comment]
@crackcomm that would be great, thanks.

**Comment by zshipko** [comment]
Nice, thanks @tizoc for figuring that out so quickly! I will merge that and make a new minor release tonight.
