### ISSUE TITLE
Issue with README?

### ISSUE THREAD

**Issue by mimoo** [zshipko/ocaml-rs#71]
Hey!

I've been wondering about this example in the README:

```
#[ocaml::func]
pub fn build_tuple(i: ocaml::Int) -> (ocaml::Int, ocaml::Int, ocaml::Int) {
    (i + 1, i + 2, i + 3)
}
```

where `ocaml::Int` seems to be defined as an `isize` in Rust. Isn't this going to pose issues when reaching values that need the full 64 bits? My understanding is that OCaml uses the last bit as tagging (unless you use `int64`).

**Comment by zshipko** [comment]
Yeah, that could be an issue, but if you think you will need the entire 64 bits you should use an `i64` instead, which converts to an OCaml `int64`

Another approach would be to define a type that wraps `isize` and checks to ensure the value is less than `max_int` in OCaml during conversion.
