### ISSUE TITLE
Calling OCaml from Rust

### ISSUE THREAD

**Issue by abrown** [zshipko/ocaml-rs#75]
I originally started looking at this project to see if I could use it to call OCaml functions from Rust. I have a static library compiled from an OCaml project and I was hoping that I would be able to call functions in it after having setup the runtime (presumably with `runtime::init`?). Can these crates be used for this purpose? What would that look like?

**Comment by zshipko** [comment]
Yes after initializing the OCaml runtime you can use ocaml-rs to call OCaml functions from Rust. On the OCaml side you would need to register the function using `Callback.register` and on the Rust side you can use `Value::named` to access the function and `Value::call` to call it.

Another option would be to use https://github.com/tezedge/ocaml-interop which provides an `ocaml!` macro (https://github.com/tezedge/ocaml-interop#call-ocaml-functions-from-rust) that helps you do something similar to the paragraph above but with more type safety.

**Comment by abrown** [comment]
Thanks! That is good to know. I have some initial code working using just `ocaml-interop` and `dune` to build the static library but it is actually good to understand how it would work with this crate. I stumbled around in the dark for a bit, bumping into different sorts of linker errors, which led me back to `ocaml-interop`, since it had an [example with build steps](https://github.com/tezedge/ocaml-interop/tree/master/testing/rust-caller). Is there something similar here? Or should something like that be added?

**Comment by zshipko** [comment]
There are some tests for calling OCaml functions from Rust, but a nice example showing how linking and everything works from the Rust side would definitely be welcome. 

Another option could be to create something similar to https://github.com/zshipko/ocaml-rust-starter that provides a basic template for a Rust project that calls into OCaml.

**Comment by zshipko** [comment]
There are now instructions for doing this in the new docs: https://zshipko.github.io/ocaml-rs/04_linking_an_ocaml_library_into_a_rust_program.html
