### ISSUE TITLE
Docs link for 0.5.0 is broken

### ISSUE THREAD

**Issue by Wilfred** [zshipko/ocaml-rs#8]
I see that [`repr(transparent)` is now stable](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1280-2018-08-02). Docs.rs [is now using rustc 1.34.0-nightly](https://docs.rs/about).

The [0.5.0 docs build failed](https://docs.rs/crate/ocaml/0.5.0/builds/115472), could you release a 0.5.1 so docs.rs builds and shows the documentation?

**Comment by zshipko** [comment]
Thanks - I just made a new release and it's updated now: https://docs.rs/ocaml/0.5.1/ocaml/
