### ISSUE TITLE
Handling of float arrays

### ISSUE THREAD

**Issue by LaurentMazare** [zshipko/ocaml-rs#88]
A tricky bit when it comes to float arrays and the OCaml runtime is that they might be represented as a "flat" array of float or as an array of boxed floats depending on how the `FLAT_FLOAT_ARRAY` variable is set.

When writing C/C++ bindings, one can use the `Double_field` and `Store_double_field` macros to appropriately get/set values from such an array, the code of the macros depend on `FLAT_FLOAT_ARRAY` as can be seen [here](https://github.com/ocaml/ocaml/blob/7ffa4cb10e62f6d708b53d6dc6a2a6c4bf7acdbe/runtime/caml/mlvalues.h#L347-L355).

It would be nice to have access to `Double_field`  and `Store_double_field` in `ocaml-sys` (as well as the value of `FLAT_FLOAT_ARRAY`) but as these are macros this is probably not straightforward to do. A C file could be added to make functions out of these macros and then expose them to Rust but I don't think there is any C file that gets compiled at the moment in `ocaml-sys` so that might be a big change.

Would you have any thoughts on how to handle float arrays with the current `ocaml-sys` crate? Maybe I'm missing some easy way around this?

**Comment by LaurentMazare** [comment]
That looks great and I think would fit my use case.
One thing I find a bit surprising is that there doesn't seem to be any function in `mlvalues.h` that would allocate a float array from the C side using the appropriate representation (i.e. with a `Double_array_tag` if `FLAT_FLOAT_ARRAY` is set and a 0 tag otherwise) but it feels that it's easy to do this on the Rust side using the newly added `ocaml_sys::FLAT_FLOAT_ARRAY` constant. Maybe it would be worth having some helper function for this?

**Comment by zshipko** [comment]
It looks like there is `CAMLextern value caml_alloc_float_array (mlsize_t len);` in `alloc.h`, I will add that as well.

**Comment by LaurentMazare** [comment]
Thanks, I only plan on using the `ocaml-sys` bit that your PR is introducing, but maybe at some point you also want to use this in the `ocaml-rs` part when converting a `Vec<f64>` to an OCaml `float array`. It seems that currently this would result in an array of boxed floats and somehow the OCaml runtime manages to use it but I ran into some issues while doing the same thing with the new [flambda backend](https://github.com/ocaml-flambda/flambda-backend).

**Comment by LaurentMazare** [comment]
Great, thanks!
