### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by c-cube** [zshipko/ocaml-rs#9]
I've been using this lib for months now, with a few opaque types behind `Box<>`, a lot of integer arguments, and the occasional creation of an OCaml array or tuple. It works great, so, thanks!

(yes,  this is not an issue, just a thank you)

**Comment by zshipko** [comment]
Awesome, glad it’s working out for you!

I know the interface isn’t as clean as it could be, so feel free to let me know if there’s anything giving you problems.

**Comment by c-cube** [comment]
I don't have any particular problem right now, I'll open an issue otherwise.
