### ISSUE TITLE
Passing int/int64/values to noalloc functions

### ISSUE THREAD

**Issue by copy** [zshipko/ocaml-rs#95]
Is it possible to pass values other than `f64` to noalloc functions? In C, I bind a noalloc functions as follows:

```ocaml
external foo :
  (int, Bigarray.int8_unsigned_elt, Bigarray.c_layout) Bigarray.Array1.t 
  -> (int64[@unboxed]) -> (int[@untagged]) -> string -> unit
  = "foo_bc" "foo" [@@noalloc]
```

```c
CAMLprim value foo(value a, int64_t b, intnat c, value d) {
    CAMLparam2(a, d);
    do_foo((Caml_ba_data_val(a), b, c, String_val(d));
    CAMLreturn(Val_unit);
}
```

Naively using `ocaml::Value` in a `extern "C"` function produces a warning (and seems to corrupt some parameters):

```
warning: `extern` fn uses type `Value`, which is not FFI-safe
  --> src/lib.rs:25:11
   |
25 |     data: ocaml::Value,
   |           ^^^^^^^^^^^^ not FFI-safe
   |
   = help: consider adding a `#[repr(C)]`, `#[repr(transparent)]`, or integer `#[repr(...)]` attribute to this enum
   = note: enum has no representation hint
```

**Comment by zshipko** [comment]
I think just adding `#[repr(C)]` should be enough to fix this? 

In the case that doesn't work you could also use `ocaml::sys::Value` or `ocaml::Raw` as the parameter and convert it to an `ocaml::Value` using `ocaml::Value::new`.

**Comment by zshipko** [comment]
I just pushed a commit to add `#[repr(C)]` to the `Value` definition. Let me know if that works!

**Comment by zshipko** [comment]
I had pushed the `#repr(C)` change but realized that `Value` no longer just wraps `sys::Value` - so that won't actually work. I think your best bet is to use `ocaml::Raw` as I mentioned above.

**Comment by copy** [comment]
> I think your best bet is to use ocaml::Raw for the parameter type as I mentioned above.

That works for me, thanks! Just curious, should I be worried about this comment:

> Convert a Raw value to Value, this should only be used in custom value destructors and other cases where you know the underlying sys::Value was created using Value::new

**Comment by zshipko** [comment]
As I understand it, `noalloc` functions don't require `CAMLparamX`/`CAMLlocalX`, which means that there is no chance of those values being garbage collected. I think this means that you're safe to avoid that comment. I should update it to note that the value should not be at risk of being GCed - either by using `Value::new` or in a `noalloc` function.

**Comment by copy** [comment]
That clears it up, cheers!
