### ISSUE TITLE
Missing `links` manifest key for ocaml-sys

### ISSUE THREAD

**Issue by gadmm** [zshipko/ocaml-rs#96]
ocaml-sys should ensure that the runtime is only linked once. This is done by adding the `links` key to the `Cargo.toml` file. See:

https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key
https://doc.rust-lang.org/cargo/reference/resolver.html#links

(Otherwise bad things could happen, such as the resolver trying to include two different versions of ocaml-sys in the same crate, AFAIU.)

**Comment by zshipko** [comment]
Thanks! It looks like I could just put `links = "ocaml"`? Or does it need to be the actual name of the linked library?

**Comment by tizoc** [comment]
@zshipko any name works, it is just metadata.

**Comment by tizoc** [comment]
See point 2 in the first enumerated list here: https://kornel.ski/rust-sys-crate

**Comment by gadmm** [comment]
I think it has to match the cargo:rustc-link-lib line from the build program.

Le 8 août 2022 18:45:29 GMT+02:00, Bruno Deferrari ***@***.***> a écrit :
***@***.*** any name works, it is just metadata.

**Comment by zshipko** [comment]
From looking some other sys crates I don’t think it’s a hard requirement that it matches the linked library name but nearly all the ones I checked do, so I set `links = “asmrun”` in sys/Cargo.toml

**Comment by gadmm** [comment]
Thanks!

**Comment by tizoc** [comment]
> From looking some other sys crates I don’t think it’s a hard requirement that it matches the linked library name

That is how I understand it. You may not be linking anything at all, or you may even be choosing between different alternative libraries, something that cannot be expressed by `package.links`.
