### ISSUE TITLE
`ocaml-build` slow because `dune` checks the `target` directories

### ISSUE THREAD

**Issue by yilinwei** [zshipko/ocaml-rs#97]
Hi,

Recently I've been trying to bootstrap a project with quite a few transitive dependencies using `ocaml-build`. It works great, but a _huge_ amount of time is spent doing `fstat` in the `/target` folder (a difference of around 800 ms when it's practically doing a no-op.

I'm not really sure whether this would be a `dune` feature, or something that would be better fixed in this library since I'm not too familiar with `dune`.

**Comment by zshipko** [comment]
Hey, thanks for the report!

I wonder if the dune `dirs` stanza could fix this: https://dune.readthedocs.io/en/stable/dune-files.html#dirs-since-1-6

I think adding `(dirs :standard \ target)` to a dune file at the root of your project should work.

**Comment by yilinwei** [comment]
I think that the `dirs` stanza is for the `dune` file not the `dune-project` file?  I got an error message when adding it to the `dune-project` file.

The `fstat` happens at the root level when the `build.rs` is calling `dune` [rust-ocaml-starter](https://github.com/zshipko/rust-ocaml-starter).

**Comment by zshipko** [comment]
I believe you can add another `dune` file to the root of your project with the dirs stanza in it.

I will try it out on the starter project and see if I can get a working example for you.

**Comment by zshipko** [comment]
Here you go: https://github.com/zshipko/rust-ocaml-starter/blob/main/dune

I've added the necessary `dune` file to both starter projects and observed improved build times. Let me know if this works for you!

**Comment by yilinwei** [comment]
Hi,

I didn't realise I could create a `dune` file in the root project!

I've verified the speedup and checked that it's not doing the `fstat` in the directories.

Thanks for the work you've put in the project and the quick turnaround on the issue!
